Battery Charger: Battery Charger Control Window
Battery Charger Control Window
Functions
BatteryChargerControl::BatteryChargerControl (AcqUnit *, QWidget *parent=0)
Constructor.
BatteryChargerControl::~BatteryChargerControl ()
void BatteryChargerControl::displayErrorMessage (const QString message)
Show an error condition in the Error label.
bool BatteryChargerControl::success ()
Successful Synchronization.
QString BatteryChargerControl::error ()
Error Message.
Private Slots
void BatteryChargerControl::on_closeButton_clicked ()
Close when quit is activated.
void BatteryChargerControl::on_acquireButton_clicked ()
Read the A/D converter information.
void BatteryChargerControl::on_uploadButton_clicked ()
Upload firmware Intel Hex file to the device through the bootloader.
void BatteryChargerControl::on_configureButton_clicked ()
Configure the Microcontroller.
void BatteryChargerControl::on_aboutButton_clicked ()
Show Microcontroller Information.
void BatteryChargerControl::on_downloadButton_clicked ()
Pull down the data saved to date.
void BatteryChargerControl::on_saveFileButton_clicked ()
Obtain a save file name and path and attempt to open it.
void BatteryChargerControl::on_closeFileButton_clicked ()
Close the save file.
Detailed Description
These functions provide functionality for the Battery Charger Control Window in which the main control and data acquisition is done. This window allows view of the current state of the charger internal variables, retrieval of stored status data and access to a number of deeper configuration dialogues.
14/2/2010 Changed the method of retrieving the channel type to match changes to the acqunit module.
Function Documentation
BatteryChargerControl::BatteryChargerControl (AcqUnit * u, QWidget * parent = 0) [inherited]
Constructor.
Parameters:
u Acquisition Unit Object
parent Parent widget.
Build the User Interface display from Ui object.
Definition at line 67 of file batterychargercontrol.cpp.
References BatteryChargerControl::on_acquireButton_clicked(), BatteryChargerControl::saveFile, BatteryChargerControl::solarRegulatorControlDialogUi, and BatteryChargerControl::unit.
void BatteryChargerControl::displayErrorMessage (const QString message) [private, inherited]
Show an error condition in the Error label.
Parameters:
[in] message Message to be displayed.
Definition at line 461 of file batterychargercontrol.cpp.
References BatteryChargerControl::solarRegulatorControlDialogUi.
Referenced by BatteryChargerControl::on_aboutButton_clicked(), BatteryChargerControl::on_acquireButton_clicked(), BatteryChargerControl::on_closeFileButton_clicked(), BatteryChargerControl::on_configureButton_clicked(), BatteryChargerControl::on_downloadButton_clicked(), BatteryChargerControl::on_saveFileButton_clicked(), and BatteryChargerControl::on_uploadButton_clicked().
QString BatteryChargerControl::error () [inherited]
Error Message.
This provides access to error messages from outside the class.
Returns:
The latest error message that was detected.
Definition at line 480 of file batterychargercontrol.cpp.
References BatteryChargerControl::errorMessage.
bool BatteryChargerControl::success () [inherited]
Successful Synchronization.
Returns:
Boolean indication that synchronization to the unit was successful.
Definition at line 470 of file batterychargercontrol.cpp.
BatteryChargerControl::~BatteryChargerControl () [inherited]
Definition at line 80 of file batterychargercontrol.cpp.
Private Slots
void BatteryChargerControl::on_aboutButton_clicked () [private, slot, inherited]
Show Microcontroller Information.
This button opens the information window.
Definition at line 250 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::solarRegulatorControlDialogUi, and BatteryChargerControl::unit.
void BatteryChargerControl::on_acquireButton_clicked () [private, slot, inherited]
Read the A/D converter information.
This function interrogates the unit to obtain the measured values of voltages and currents that it is currently using, as well as internal state variables of interest.
The instantaneous values are stored in the internal EEPROM in the channel information block.
Definition at line 104 of file batterychargercontrol.cpp.
References BatteryChargerControl::averageValue, BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::solarRegulatorControlDialogUi, and BatteryChargerControl::unit.
Referenced by BatteryChargerControl::BatteryChargerControl().
void BatteryChargerControl::on_closeButton_clicked () [private, slot, inherited]
Close when quit is activated.
Definition at line 88 of file batterychargercontrol.cpp.
void BatteryChargerControl::on_closeFileButton_clicked () [private, slot, inherited]
Close the save file.
Wipe the name to prevent same file being used.
Disable the buttons
Definition at line 438 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::outFile, BatteryChargerControl::saveFile, and BatteryChargerControl::solarRegulatorControlDialogUi.
void BatteryChargerControl::on_configureButton_clicked () [private, slot, inherited]
Configure the Microcontroller.
This button opens the configure window.
Definition at line 237 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::solarRegulatorControlDialogUi, and BatteryChargerControl::unit.
void BatteryChargerControl::on_downloadButton_clicked () [private, slot, inherited]
Pull down the data saved to date.
Download the DAU buffer contents to the save file. The DAU will reset the buffer pointers, thus freeing up buffer space. If the unit had been powered off, the pointers will be invalid. In that case use offline mode to access the pointers in the EEPROM and so recover the data. We don't use this method normally as reading the buffer during an active conversion process requires the pointers to be read and immediately reset so that further writes to the buffer will not be consistent.
Check that the save file has been defined and is open.
If offline, we need to grab the pointers from the external EEPROM.
Otherwise use the pointers maintained by the process. The DAU will return the pointers and reset them to make a zero length queue.
Find the number of milliseconds in a real time clock tick.
Read in the buffer data using the pointers and a simple block EEPROM read command.
Then interpret the results and write the resulting buffer to the file.
Definition at line 269 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::outFile, BatteryChargerControl::saveFile, BatteryChargerControl::solarRegulatorControlDialogUi, BatteryChargerControl::startTime, and BatteryChargerControl::unit.
void BatteryChargerControl::on_saveFileButton_clicked () [private, slot, inherited]
Obtain a save file name and path and attempt to open it.
Make sure there is no file already open.
If the output file exists, then we are asking for it to be updated with new data from the Unit. We also need to check that it is a valid data file.
If the output file does not exist, then create it.
Definition at line 386 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::outFile, BatteryChargerControl::saveDirectory, BatteryChargerControl::saveFile, and BatteryChargerControl::solarRegulatorControlDialogUi.
void BatteryChargerControl::on_uploadButton_clicked () [private, slot, inherited]
Upload firmware Intel Hex file to the device through the bootloader.
This button sends a command to force the unit to jump to the bootloader, aborting any actions that are currently in progress.
The bootloader window is opened and bootloader commands are used.
After the bootloader window is closed, we must resynchronize.
Definition at line 220 of file batterychargercontrol.cpp.
References BatteryChargerControl::displayErrorMessage(), BatteryChargerControl::solarRegulatorControlDialogUi, and BatteryChargerControl::unit.