Battery Charger: Battery Charger Calibration Window
Battery Charger Calibration Window
Functions
BatteryChargerCalibrate::BatteryChargerCalibrate (AcqSimpleAdcUnit *, QWidget *parent=0)
Constructor.
BatteryChargerCalibrate::~BatteryChargerCalibrate ()
Private Slots
void BatteryChargerCalibrate::on_closeButton_clicked ()
Close when OK is activated returning success.
void BatteryChargerCalibrate::on_firstValueLineEdit_textChanged ()
Enable the first entry button when the text changes.
void BatteryChargerCalibrate::on_secondValueLineEdit_textChanged ()
Enable the compute button when the text changes.
void BatteryChargerCalibrate::on_firstValueSetButton_clicked ()
Read the first calibration value from the unit.
void BatteryChargerCalibrate::on_secondValueSetButton_clicked ()
Read the second calibration value from the unit.
void BatteryChargerCalibrate::on_clearEntriesButton_clicked ()
Clear all the entries and start again.
void BatteryChargerCalibrate::on_commitButton_clicked ()
Commit the scaling factors to the unit.
void BatteryChargerCalibrate::displayErrorMessage (const QString)
Error Message.
Detailed Description
These functions provide functionality for the Battery Charger Calibration Window in which the analogue channels are calibrated against known voltages and currents, and conversion parameters are computed and programmed into the channel information blocks of the unit.
Function Documentation
BatteryChargerCalibrate::BatteryChargerCalibrate (AcqSimpleAdcUnit * u, QWidget * parent = 0) [inherited]
Constructor.
Check if the channel exists in the unit. If not, create a default entry. We need to do this because the unit will not present any measurements until it has a channel to work on.
Parameters:
u Acquisition Unit Object
parent Parent widget.
Build the User Interface display from Ui object.
Definition at line 47 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi, BatteryChargerCalibrate::channelUnit, BatteryChargerCalibrate::displayErrorMessage(), BatteryChargerCalibrate::firstEntered, and BatteryChargerCalibrate::on_clearEntriesButton_clicked().
BatteryChargerCalibrate::~BatteryChargerCalibrate () [inherited]
Definition at line 72 of file batterychargercalibrate.cpp.
Private Slots
void BatteryChargerCalibrate::displayErrorMessage (const QString message) [private, slot, inherited]
Error Message.
This provides access to error messages from outside the class.
Returns:
The latest error message that was detected.
Definition at line 209 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi.
Referenced by BatteryChargerCalibrate::BatteryChargerCalibrate(), BatteryChargerCalibrate::on_commitButton_clicked(), BatteryChargerCalibrate::on_firstValueSetButton_clicked(), and BatteryChargerCalibrate::on_secondValueSetButton_clicked().
void BatteryChargerCalibrate::on_clearEntriesButton_clicked () [private, slot, inherited]
Clear all the entries and start again.
Definition at line 182 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi.
Referenced by BatteryChargerCalibrate::BatteryChargerCalibrate().
void BatteryChargerCalibrate::on_closeButton_clicked () [private, slot, inherited]
Close when OK is activated returning success.
Definition at line 80 of file batterychargercalibrate.cpp.
void BatteryChargerCalibrate::on_commitButton_clicked () [private, slot, inherited]
Commit the scaling factors to the unit.
Definition at line 195 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::channelUnit, and BatteryChargerCalibrate::displayErrorMessage().
void BatteryChargerCalibrate::on_firstValueLineEdit_textChanged () [private, slot, inherited]
Enable the first entry button when the text changes.
Only if the entered value makes a valid floating point number. If it is not valid then disable it.
Definition at line 92 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi, and BatteryChargerCalibrate::firstValue.
void BatteryChargerCalibrate::on_firstValueSetButton_clicked () [private, slot, inherited]
Read the first calibration value from the unit.
The unit is interrogated for the smoothed A/D reading for the channel to match with the first measurement. The second value set button is then enabled and the first is disabled.
Definition at line 129 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi, BatteryChargerCalibrate::channelUnit, BatteryChargerCalibrate::displayErrorMessage(), BatteryChargerCalibrate::firstEntered, and BatteryChargerCalibrate::firstSample.
void BatteryChargerCalibrate::on_secondValueLineEdit_textChanged () [private, slot, inherited]
Enable the compute button when the text changes.
Only if the entered value makes a valid floating point number, and the first value is also valid and has been successfully entered. If it is not valid, then disable it.
Definition at line 109 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi, BatteryChargerCalibrate::firstEntered, BatteryChargerCalibrate::firstValue, and BatteryChargerCalibrate::secondValue.
void BatteryChargerCalibrate::on_secondValueSetButton_clicked () [private, slot, inherited]
Read the second calibration value from the unit.
The unit is interrogated for the smoothed A/D reading for the channel. This is then combined with the first value to determine the scaling factors and the maximum and minimum of the range is displayed. The commit button is enabled.
Definition at line 153 of file batterychargercalibrate.cpp.
References BatteryChargerCalibrate::BatteryChargerCalibrateDialogueUi, BatteryChargerCalibrate::channelUnit, BatteryChargerCalibrate::displayErrorMessage(), BatteryChargerCalibrate::firstSample, BatteryChargerCalibrate::firstValue, BatteryChargerCalibrate::secondSample, and BatteryChargerCalibrate::secondValue.