BatteryCharger: batterychargermain-working.c File Reference
batterychargermain-working.c File Reference
#include <inttypes.h>
#include <avr/sfr_defs.h>
#include <avr/eeprom.h>
#include <avr/io.h>
#include <avr/wdt.h>
#include <avr/interrupt.h>
#include "solarregulatormain.h"
#include "lcd/lcd-HD44780.h"
#include "uart/uart.h"
#include "timer/timer.h"
#include "twi/i2c.h"
#include "nartos/nartos.h"
Data Structures
union timeUnion
Defines
#define TRUE 1
#define FALSE 0
#define _BV(bit) (1 << (bit))
#define inb(sfr) _SFR_BYTE(sfr)
#define inw(sfr) _SFR_WORD(sfr)
#define outb(sfr, val) (_SFR_BYTE(sfr) = (val))
#define outw(sfr, val) (_SFR_WORD(sfr) = (val))
#define cbi(sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
#define sbi(sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
#define high(x) ((uint8_t) (x >> 8) & 0xFF)
#define low(x) ((uint8_t) (x & 0xFF))
Functions
int main (void)
Main Program.
void initiateControlTask (void)
Launch the Control task.
void measurementTask (void)
Measurement task.
void controlTask (void)
Control task.
void displayTask (void)
Display task.
void processError (void)
Error Processing task.
void processCommand (void)
Input Packet Interpretation Processing task.
void inputPacketReceive (void)
PC Communication Input task.
void outputPacketSend (void)
PC Communication Output task.
ISR (SIG_OVERFLOW0)
Timer 0 ISR.
long rescale (const int quantity, const int multiplier, const int offset)
Scale a measured A/D quantity.
void display (const long value)
Display a 32 bit value as decimal on the LCD.
void setErrorCode (const unsigned int code)
Set the Error Code.
void configurePorts (void)
Configure the ports to match hardware.
void openPanel (void)
Port B output 0 when high will open the panel for charging.
void shortPanel (void)
Port B output 0 when low will short the panel.
void connectLoad (void)
Port B output 1 when low will connect the battery to the load.
void isolateLoad (void)
Port B output 1 when high will isolate the load.
void onLED (void)
Port B output 1 when low will turn off a LED.
void offLED (void)
Port B output 2 when high will turn on a LED.
Variables
union timeUnion time
Timer Counters
volatile uint16_t controlDelayCounter = 0
volatile uint16_t controlTaskCounter = 0
volatile uint16_t controlInterval = 0
volatile uint16_t displayDelayCounter = 0
volatile uint16_t displayTaskCounter = 0
volatile uint16_t displayInterval = 0
volatile uint16_t measurementTaskCounter = 0
volatile uint16_t measurementInterval = 0
UART variables
volatile uint16_t uartInput
volatile uint8_t lastError
volatile uint8_t checkSum
Input state machine variables
volatile uint8_t packetInState
volatile uint8_t numberInBytes
volatile uint8_t dataInByteCount
volatile uint8_t inputCommand
volatile uint8_t inputBuffer [DATA_BUFFER_SIZE]
Output state machine variables
volatile uint8_t outputBusy
volatile uint8_t packetOutState
volatile uint8_t numberOutBytes
volatile uint8_t dataOutByteCount
volatile uint8_t outputCommand
volatile uint8_t outputBuffer [DATA_BUFFER_SIZE]
Task IDs
volatile uint8_t inputPacketReceiveID
volatile uint8_t outputPacketSendID
volatile uint8_t processCommandID
volatile uint8_t processErrorID
volatile uint8_t initiateControlTaskID
volatile uint8_t controlTaskID
volatile uint8_t measurementTaskID
volatile uint8_t displayTaskID
Command specific variables
volatile uint8_t eepromCount
const uint8_t * address
volatile uint8_t adcControlByte
volatile uint8_t adcChannel
volatile uint16_t bufferStartPointer = BUFFER_START
volatile uint16_t bufferEndPointer = BUFFER_START
volatile uint16_t newBufferEndPointer
volatile uint8_t shift
volatile uint16_t numberConversions
Task global variables
volatile uint8_t rtcScale
volatile uint8_t localEEPROMDevice
volatile uint16_t eepromEnd
volatile uint8_t adcShift
volatile uint16_t channelValue [4]
volatile uint16_t scaledChannelValue [4]
Define Documentation
#define _BV (bit) (1 << (bit))
Definition at line 63 of file batterychargermain-working.c.
#define cbi (sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
Definition at line 68 of file batterychargermain-working.c.
#define FALSE 0
Definition at line 61 of file batterychargermain-working.c.
#define high (x) ((uint8_t) (x >> 8) & 0xFF)
Definition at line 70 of file batterychargermain-working.c.
#define inb (sfr) _SFR_BYTE(sfr)
Definition at line 64 of file batterychargermain-working.c.
#define inw (sfr) _SFR_WORD(sfr)
Definition at line 65 of file batterychargermain-working.c.
#define low (x) ((uint8_t) (x & 0xFF))
Definition at line 71 of file batterychargermain-working.c.
#define outb (sfr, val) (_SFR_BYTE(sfr) = (val))
Definition at line 66 of file batterychargermain-working.c.
#define outw (sfr, val) (_SFR_WORD(sfr) = (val))
Definition at line 67 of file batterychargermain-working.c.
#define sbi (sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
Definition at line 69 of file batterychargermain-working.c.
#define TRUE 1
Definition at line 60 of file batterychargermain-working.c.
Function Documentation
void controlTask (void)
Control task.
This task runs the main control of the Regulator and relinquishes when possible to allow serial input and output to occur. This task has absolute priority.
This is a test version to check battery operation. The battery voltage is measured as a sequence of rapid measurements that are averaged, then the load is disconnected. Every 100ms a measurement is taken until the voltage has settled. This can then be used to determine the capacity.
Under normal conditions the load would not be disconnected until the voltage drops below a critical level.
Write the new pointers to their location in EEPROM. We do this before rather than after the A/D converted values are stored, because after a write to the I2c bus has been executed, an indeterminate delay is needed for the bus to become free (following a stop condition that is never signalled). We are safer to use the A/D conversions to provide that delay.
Firstly check if the buffer is full if it is a blocking buffer, then compute a new end pointer that would hold after a data block is written
Definition at line 348 of file batterychargermain-working.c.
References BUFFER_START, bufferEndPointer, bufferStartPointer, controlDelayCounter, DATA_BLOCK_SIZE, eepromEnd, FALSE, floatThreshold, high, localEEPROMDevice, low, measurementTask(), measurementTaskID, newBufferEndPointer, openPanel(), scaledChannelValue, shortPanel(), time, and timeUnion::timeByte.
void display (const long value)
Display a 32 bit value as decimal on the LCD.
The value is an A/D conversion result. 16 bits represents a value out of 100 and 3 decimal digits are displayed as appropriate for a 10 bit A/D converter.
: 32 bit integer value to be converted
Definition at line 1237 of file batterychargermain-working.c.
void displayTask (void)
Display task.
Display and Data Capture task.
This task tests for user input via a hardware push button and manages the display of system variables and configuration of certain items.
Compute new buffer pointers and write to their location in EEPROM.
Compute a new end pointer that would hold after a data block is written. If we can't fit it into the end, put it at the start of the memory buffer.
Definition at line 430 of file batterychargermain-working.c.
References display(), and scaledChannelValue.
void initiateControlTask (void)
Launch the Control task.
This task sets up the main tasks by initializing the EEPROM storage. When ready it initiates the tasks to run regularly and check the battery voltage. This task then terminates.
Setup the external EEPROM for storing the samples. The first 16 bytes are reserved for general control information which includes the buffer pointers needed to recover data when power fails. These pointers are held in locations 8 to 11.
Definition at line 224 of file batterychargermain-working.c.
References adcShift, BUFFER_START, bufferEndPointer, bufferStartPointer, controlDelayCounter, controlTask(), controlTaskID, displayInterval, displayTask(), displayTaskCounter, displayTaskID, FALSE, high, localEEPROMDevice, low, setErrorCode(), and WRITE_EEPROM_FAIL.
void inputPacketReceive (void)
PC Communication Input task.
This task waits for an incoming character on the UART, and packages it up into a message.
Low level input interface errors are ignored and such characters are lost. The input state machine works through the packet stages as characters arrive. Parameters are read in and the syntax of the packet is checked. The packet data is stored in a buffer for later interpretation. Input is blocked when the packet has been fully read in. The buffer holds one single packet in full. This allows us to discard the packet when an error occurs. A circular buffer makes error recovery very difficult.
If an error occurs, the packetInState must be returned to IDLE but the input task must not be blocked.
The task never exits, but acts as a monitoring task that activates other tasks as appropriate. This task is not entered if the error or command processing tasks are active. If there are no incoming characters waiting, the task relinquishes.
The idle state occurs on startup, after a command has been received fully, or when an error has occurred. When an IDLE character is received, it is echoed back if the current output is not processing anything. The sync state is terminated. The next state, SYNC, is entered. In any other case, usually flushing after an error, the character is ignored.
If a SYNC character is received, go to the COMMAND state. We can accept IDLE characters and ignore them, otherwise return to the IDLE state and flush all following characters (no error is generated)
The address+packet type tells us if the packet is addressed to us. Just accept any address for the moment until we get a means to find out who we are. The packet type is also ignored until we define more types.
If the byte count is zero (no parameters), terminate the packet, otherwise go on to the data phase.
Put the command aside and go to the data phase if more characters follow
In the DATA phase just dump everything to the buffer if it will fit. dataInByteCount points to the next location to add a byte.
Todo:
We ignore the checksum for the moment
EOM terminates the packet, and we should have an EOM character here. We can now start up the packet interpretation task, blocking any further input processing. If an error has occurred,the error task will unblock this.
Definition at line 999 of file batterychargermain-working.c.
References ADDRESS, CHECKSUM, COMMAND, COMMAND_SYNTAX, DATA_BUFFER_SIZE, DATA_PHASE, dataInByteCount, EOM, EOM_CHAR, FALSE, high, IDLE, IDLE_CHAR, inputBuffer, inputCommand, lastError, NUMBER_BYTES, numberInBytes, numberOutBytes, outputBuffer, outputBusy, packetInState, processCommand(), processCommandID, processError(), processErrorID, SYNC, SYNC_CHAR, and uartInput.
ISR (SIG_OVERFLOW0)
Timer 0 ISR.
This ISR updates the RTC time, and reschedules any tasks that have been suspended pending a timeout interval. It also manages the counters that can schedule tasks according to the program functions.
The counters are decremented and a task restart operation occurs when they reach zero. Reset the counter here if the operation is repetitive.
Definition at line 1169 of file batterychargermain-working.c.
References controlDelayCounter, controlTaskID, displayInterval, displayTask(), displayTaskCounter, displayTaskID, time, timeUnion::timeValue, and TRUE.
int main (void)
Main Program.
This sets up the interfaces for EEPROM and RTC
Initialise some variables
Setup the I/O ports, ADC, TWI, timer and LCD.
Initialize the UART library, pass the baudrate and avr cpu clock (uses the macro UART_BAUD_SELECT()). Set the baudrate to a predefined value.
Enable interrupts, since the UART library is interrupt controlled.
Set input and output state variables to their idle state.
Initialise the OS stuff, setup the control and receive tasks, and jump to the OS. The control task must be initiated first.
Definition at line 161 of file batterychargermain-working.c.
References ADC_MODE, ADC_SPEED, BAUDRATE, configurePorts(), connectLoad(), EEPROM_END, eepromEnd, FALSE, IDLE, initiateControlTask(), initiateControlTaskID, inputPacketReceive(), inputPacketReceiveID, lastError, LOCAL_EEPROM_DEVICE, localEEPROMDevice, NO_COMMAND, NO_ERROR, openPanel(), outputBusy, outputCommand, packetInState, packetOutState, RTC_SCALE, rtcScale, setErrorCode(), time, timeUnion::timeValue, and TWI_SPEED.
void measurementTask (void)
Measurement task.
This task measures the voltages and currents from the A/D converters, and scales them according to the calibrated values in the internal EEPROM block.
In the event of an error, we will not add in any measured value, but we must be able to account for the missing elements. We do this by keeping a count of errored values, and when we get a good value, fill in the previous missing values with multiple copies of it. Such errors are never signalled back.
The summed results need to be scaled back to 10 bits to match the A/D precision.
The scaled result according to calibration is also stored for display.
Definition at line 276 of file batterychargermain-working.c.
References _BV, adcErrorCount, adcShift, channel, channelStart, channelSum, channelValue, controlTaskID, FALSE, numberChannels, rescale(), sampleCount, and scaledChannelValue.
void outputPacketSend (void)
PC Communication Output task.
This task transmits any characters found to be in the output buffer. Normally it is not activated until an entire message is ready to go.
Check for an active output command. If none, but an error is signalled, send error message. Each command requires a response so a packet is generated. Use a state machine to work through the stages when output buffer is free.
The task exits after the message has been sent.
Definition at line 1098 of file batterychargermain-working.c.
References ADDRESS, CHECKSUM, checkSum, COMMAND, DATA_PHASE, dataOutByteCount, EOM, EOM_CHAR, FALSE, IDLE, IDLE_CHAR, NO_COMMAND, NUMBER_BYTES, numberOutBytes, outputBuffer, outputBusy, outputCommand, packetOutState, SYNC, SYNC_CHAR, and TRUE.
void processCommand (void)
Input Packet Interpretation Processing task.
This is where the command interpretation is done, causing a number of tasks to be initiated. The task is scheduled when the input data buffer has something in it. The input buffer has the parameters and the data following. Use a state machine approach as it gives simpler code.
Wait until all pending Input and Output processes are complete.
For each command, the number of expected parameters is checked in some way.
Unit Information Block Access data. No parameters. This command returns the address of the start of the information block, its length and the size of the largest block that can be transferred. Following this is the unit ID read from the on-board switches.
Read Internal EEPROM Memory. Parameters: two byte address to access data, and number of data bytes to be read, accounting for limits. This command returns the contents of a block of internal EEPROM memory.
Write Internal EEPROM Memory. Parameters: two byte address to access data, followed by all data bytes to be written. Expect at least 1 and no more than DATA_BUFFER_SIZE-3 data bytes to follow. This command writes the contents of a block of internal EEPROM memory.
Read External EEPROM. Parameters: two byte address to access data followed by device address of external EEPROM, and the number of data bytes to be read, accounting for limits. This command returns the contents of a block of external EEPROM memory. The variable eepromCount contains the number of bytes to be read from the EEPROM. The twiSetupTransaction, twiWriteByte functions are nonblocking.
Write External EEPROM command. Parameters: address to access data, followed by device ID and number of bytes and all data bytes to be written. This command writes the contents of a block of external EEPROM memory. Expect at least 1 and no more than DATA_BUFFER_SIZE-4 data bytes to follow.
Initiate a single A/D conversion. One single A/D conversion is done. Parameters: channel number, Gain (not used). Result: Timer 4 bytes, A/D result 2 bytes.
Return Data Block of Current State.
Parameters: none. Result: Length in bytes of data block A block of internal state variables selected according to application. In this case, four averaged A/D measurements, 2 bytes each, unscaled.
Reset the circular buffer pointers.
This command returns the buffer start and end pointers, then sets the start pointer to the end pointer. This effectively sets the buffer to empty. The calling program is then expected to immediately read in all data between the old start and end pointers to ensure that nothing is overwritten. Parameters: none. Result: none.
Reset the Real Time Clock. No parameters.
Jump to the bootloader. This command causes the program to transfer control to the bootloader. Its purpose is to enable firmware uploads at any time. For the AVR MCU this is done by setting the MCU watchdog timer for the shortest period, and continuing its business. A watchdog timer reset will occur pushing it into the bootloader where the wdt will be disabled. This is unsatisfactory but necessary as the compiler could not handle a long jump.
Command not recognized. Returns an error code.
If an error occurred, launch the error processing task, else launch the output transmission task. Follow by rescheduling the suspended receive task.
Definition at line 484 of file batterychargermain-working.c.
References ADC_FAILURE, ADC_ONCE, ADC_SYNTAX, adcChannel, address, BOOT_SYNTAX, BOOTLOADER_JUMP, bufferEndPointer, bufferStartPointer, cbi, channel, channelValue, CLEAR_PORT_BIT, DATA_BUFFER_SIZE, eepromCount, F_CPU, FALSE, high, inb, INF_BLOCK_START, inputBuffer, inputCommand, inputPacketReceiveID, lastError, low, NO_ERROR, NO_PORT, numberInBytes, numberOutBytes, outputBuffer, outputBusy, outputCommand, outputPacketSend(), outputPacketSendID, processError(), READ_EEPROM, READ_EEPROM_FAIL, READ_EEPROM_SYNTAX, READ_MEMORY, READ_MEMORY_SYNTAX, READ_PORT, READ_PORT_SYNTAX, READ_SRAM, READ_SRAM_SYNTAX, RESET_BUFFER_POINTERS, RESET_BUFFER_POINTERS_SYNTAX, RESET_CLOCK, RESET_CLOCK_SYNTAX, rtcScale, sbi, SET_PORT_BIT, STATE_VARIABLE_SYNTAX, STATE_VARIABLES, SUCCESS_COMMAND, time, timeUnion::timeByte, timeUnion::timeValue, UNIT_INF_ACCESS, UNIT_INF_ACCESS_SYNTAX, UNKNOWN_COMMAND, WRITE_EEPROM, WRITE_EEPROM_FAIL, WRITE_EEPROM_SYNTAX, WRITE_MEMORY, and WRITE_MEMORY_SYNTAX.
void processError (void)
Error Processing task.
If an error has occurred, reset the input buffer and build an error message to be output. Wait for any output processing to finish. Input processing continues but not packet interpretation.
The program can place any number of explanatory bytes in the output buffer from location 1 onwards, setting numberBytes to the number of additional bytes. This is incremented again to cover the additional error code at location 0.
The task completes processing of the command and exits. It is activated by the input task when a message has been received.
Definition at line 460 of file batterychargermain-working.c.
References ERROR_COMMAND, FALSE, inputPacketReceiveID, lastError, NO_ERROR, numberOutBytes, outputBuffer, outputBusy, outputCommand, outputPacketSend(), and outputPacketSendID.
long rescale (const int quantity, const int multiplier, const int offset)
Scale a measured A/D quantity.
The version of gcc used doesn't correctly multiply two 16 bit numbers to give a 32 bit result, but truncates it. This performs the necessary scaling by working out the 16 bit products of the 8 two 8 bit parts, then combining the necessary shift of 10 bits into the shifts needed to renormalize the products. The result is a 16 bit scaled result with the offset added.
Definition at line 1208 of file batterychargermain-working.c.
References high, and low.
void setErrorCode (const unsigned int code)
Set the Error Code.
An error code is set in the internal EEPROM for access by a monitor. An LED state is modified to indicate presence of an error. A message is displayed on the LCD screen with the code.
Definition at line 1264 of file batterychargermain-working.c.
References offLED(), and onLED().
Variable Documentation
volatile uint8_t adcChannel
Channel to be converted
Definition at line 142 of file batterychargermain-working.c.
volatile uint8_t adcControlByte
Mask for channels to be converted
Definition at line 141 of file batterychargermain-working.c.
volatile uint8_t adcShift
Definition at line 154 of file batterychargermain-working.c.
const uint8_t* address
Address for EEPROM access
Definition at line 140 of file batterychargermain-working.c.
volatile uint16_t bufferEndPointer = BUFFER_START
Data buffer pointer
Definition at line 144 of file batterychargermain-working.c.
volatile uint16_t bufferStartPointer = BUFFER_START
Data buffer pointer
Definition at line 143 of file batterychargermain-working.c.
volatile uint16_t channelValue[4]
Definition at line 155 of file batterychargermain-working.c.
volatile uint8_t checkSum
Checksum on message contents
Definition at line 107 of file batterychargermain-working.c.
volatile uint16_t controlDelayCounter = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 91 of file batterychargermain-working.c.
volatile uint16_t controlInterval = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 93 of file batterychargermain-working.c.
volatile uint16_t controlTaskCounter = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 92 of file batterychargermain-working.c.
volatile uint8_t controlTaskID
Definition at line 133 of file batterychargermain-working.c.
volatile uint8_t dataInByteCount
Substate variable for data phase
Definition at line 113 of file batterychargermain-working.c.
volatile uint8_t dataOutByteCount
Substate variable for data phase
Definition at line 122 of file batterychargermain-working.c.
volatile uint16_t displayDelayCounter = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 94 of file batterychargermain-working.c.
volatile uint16_t displayInterval = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 96 of file batterychargermain-working.c.
volatile uint16_t displayTaskCounter = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 95 of file batterychargermain-working.c.
volatile uint8_t displayTaskID
Definition at line 135 of file batterychargermain-working.c.
volatile uint8_t eepromCount
Databytes to read/write to EEPROM
Definition at line 139 of file batterychargermain-working.c.
volatile uint16_t eepromEnd
Definition at line 153 of file batterychargermain-working.c.
volatile uint8_t initiateControlTaskID
Definition at line 132 of file batterychargermain-working.c.
volatile uint8_t inputBuffer[DATA_BUFFER_SIZE]
Incoming data buffer
Definition at line 115 of file batterychargermain-working.c.
volatile uint8_t inputCommand
Command given by PC
Definition at line 114 of file batterychargermain-working.c.
volatile uint8_t inputPacketReceiveID
Definition at line 128 of file batterychargermain-working.c.
volatile uint8_t lastError
Error code for transmission back
Definition at line 106 of file batterychargermain-working.c.
volatile uint8_t localEEPROMDevice
Definition at line 152 of file batterychargermain-working.c.
volatile uint16_t measurementInterval = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 98 of file batterychargermain-working.c.
volatile uint16_t measurementTaskCounter = 0
Counters available for timer functions. Timing is disabled if the value is initially set to zero. Enable it by setting it to the timeout value required.
Definition at line 97 of file batterychargermain-working.c.
volatile uint8_t measurementTaskID
Definition at line 134 of file batterychargermain-working.c.
volatile uint16_t newBufferEndPointer
Databytes to read/write to EEPROM
Definition at line 145 of file batterychargermain-working.c.
volatile uint16_t numberConversions
Databytes to read/write to EEPROM
Definition at line 147 of file batterychargermain-working.c.
volatile uint8_t numberInBytes
Number of parameter bytes in packet
Definition at line 112 of file batterychargermain-working.c.
volatile uint8_t numberOutBytes
Number of parameter bytes in packet
Definition at line 121 of file batterychargermain-working.c.
volatile uint8_t outputBuffer[DATA_BUFFER_SIZE]
Outgoing data Buffer
Definition at line 124 of file batterychargermain-working.c.
volatile uint8_t outputBusy
Boolean to lock output
Definition at line 119 of file batterychargermain-working.c.
volatile uint8_t outputCommand
Command sent to PC
Definition at line 123 of file batterychargermain-working.c.
volatile uint8_t outputPacketSendID
Definition at line 129 of file batterychargermain-working.c.
volatile uint8_t packetInState
State variable for input machine
Definition at line 111 of file batterychargermain-working.c.
volatile uint8_t packetOutState
State variable for output machine
Definition at line 120 of file batterychargermain-working.c.
volatile uint8_t processCommandID
Definition at line 130 of file batterychargermain-working.c.
volatile uint8_t processErrorID
Definition at line 131 of file batterychargermain-working.c.
volatile uint8_t rtcScale
Definition at line 151 of file batterychargermain-working.c.
volatile uint16_t scaledChannelValue[4]
Definition at line 156 of file batterychargermain-working.c.
volatile uint8_t shift
Databytes to read/write to EEPROM
Definition at line 146 of file batterychargermain-working.c.
union timeUnion time
Real Time Clock Global Variable
The 32 bit time can also be accessed as four bytes. Time scale is defined in the information block.
volatile uint16_t uartInput
Character and errorcode read from uart
Definition at line 105 of file batterychargermain-working.c.