BatteryCharger: Interface Functions
Interface Functions
Functions
void display (const long value)
Display a 32 bit value as decimal on the LCD.
void setErrorCode (const unsigned int code)
Set the Error Code.
Detailed Description
These provide some local display and input functionsmainly for the LCD panel and push buttons.
Function Documentation
void display (const long value)
Display a 32 bit value as decimal on the LCD.
The value is an A/D conversion result. 16 bits represents a value out of 100 and 3 decimal digits are displayed as appropriate for a 10 bit A/D converter.
Parameters:
value 32 bit integer value to be converted
Definition at line 1297 of file batterychargermain.c.
Referenced by displayTask().
void setErrorCode (const unsigned int code)
Set the Error Code.
An error code is set in the internal EEPROM for access by a monitor. An LED state is modified to indicate presence of an error. A message is displayed on the LCD screen with the code.
Definition at line 1324 of file batterychargermain.c.
References offLED(), and onLED().
Referenced by initiateControlTask(), and main().