BatteryCharger: Serial Communication and Interpretation Tasks
Serial Communication and Interpretation Tasks
Functions
void processError (void)
Error Processing task.
void processCommand (void)
Input Packet Interpretation Processing task.
void inputPacketReceive (void)
PC Communication Input task.
void outputPacketSend (void)
PC Communication Output task.
Detailed Description
These functions provide the serial communication interface including packet level interpretation and buffering, and command processing and execution.
These functions are common to this and the Acquisition and Solar Regulator projects. Some command actions may be different.
Function Documentation
void inputPacketReceive (void)
PC Communication Input task.
This task waits for an incoming character on the UART, and packages it up into a message.
Low level input interface errors are ignored and such characters are lost. The input state machine works through the packet stages as characters arrive. Parameters are read in and the syntax of the packet is checked. The packet data is stored in a buffer for later interpretation. Input is blocked when the packet has been fully read in. The buffer holds one single packet in full. This allows us to discard the packet when an error occurs. A circular buffer would make such error recovery very difficult.
If an error occurs, the packetInState must be returned to IDLE but the input task must not be blocked.
The task never exits, but acts as a monitoring task that activates other tasks as appropriate. This task is not entered if the error or command processing tasks are active. If there are no incoming characters waiting, the task relinquishes.
The idle state occurs on startup, after a command has been received fully, or when an error has occurred. When an IDLE character is received, it is echoed back if the current output is not processing anything. The sync state is terminated. The next state, SYNC, is entered. In any other case, usually flushing after an error, the character is ignored.
If a SYNC character is received, go to the COMMAND state. We can accept IDLE characters and ignore them, otherwise return to the IDLE state and flush all following characters (no error is generated)
The address+packet type tells us if the packet is addressed to us. Just accept any address for the moment until we get a means to find out who we are. The packet type is also ignored until we define more types.
If the byte count is zero (no parameters), terminate the packet, otherwise go on to the data phase.
Put the command aside and go to the data phase if more characters follow
In the DATA phase just dump everything to the buffer if it will fit. dataInByteCount points to the next location to add a byte.
Todo:
We ignore the checksum for the moment
EOM terminates the packet, and we should have an EOM character here. We can now start up the packet interpretation task, blocking any further input processing. If an error has occurred,the error task will unblock this.
Definition at line 1066 of file batterychargermain.c.
References ADDRESS, CHECKSUM, COMMAND, COMMAND_SYNTAX, DATA_BUFFER_SIZE, DATA_PHASE, dataInByteCount, EOM, EOM_CHAR, FALSE, high, IDLE, IDLE_CHAR, inputBuffer, inputCommand, lastError, NUMBER_BYTES, numberInBytes, numberOutBytes, outputBuffer, outputBusy, packetInState, processCommand(), processCommandID, processError(), processErrorID, SYNC, SYNC_CHAR, and uartInput.
Referenced by main().
void outputPacketSend (void)
PC Communication Output task.
This task transmits any characters found to be in the output buffer. Normally it is not activated until an entire message is ready to go.
Check for an active output command. If none, but an error is signalled, send error message. Each command requires a response so a packet is generated. Use a state machine to work through the stages when output buffer is free.
The task exits after the message has been sent.
Definition at line 1165 of file batterychargermain.c.
References ADDRESS, CHECKSUM, checkSum, COMMAND, DATA_PHASE, dataOutByteCount, EOM, EOM_CHAR, FALSE, IDLE, IDLE_CHAR, NO_COMMAND, NUMBER_BYTES, numberOutBytes, outputBuffer, outputBusy, outputCommand, packetOutState, SYNC, SYNC_CHAR, and TRUE.
Referenced by processCommand(), and processError().
void processCommand (void)
Input Packet Interpretation Processing task.
This is where the command interpretation is done, causing a number of tasks to be initiated. The task is scheduled when the input data buffer has something in it. The input buffer has the parameters and the data following. Use a state machine approach as it gives simpler code.
Wait until all pending Input and Output processes are complete.
For each command, the number of expected parameters is checked in some way.
Unit Information Block Access data. No parameters. This command returns the address of the start of the information block, its length and the size of the largest block that can be transferred. Following this is the unit ID read from the on-board switches.
Read Internal EEPROM Memory. Parameters: two byte address to access data, and number of data bytes to be read, accounting for limits. This command returns the contents of a block of internal EEPROM memory.
Write Internal EEPROM Memory. Parameters: two byte address to access data, followed by all data bytes to be written. Expect at least 1 and no more than DATA_BUFFER_SIZE-3 data bytes to follow. This command writes the contents of a block of internal EEPROM memory.
Read External EEPROM. Parameters: two byte address to access data followed by device address of external EEPROM, and the number of data bytes to be read, accounting for limits. This command returns the contents of a block of external EEPROM memory. The variable eepromCount contains the number of bytes to be read from the EEPROM. The twiSetupTransaction, twiWriteByte functions are nonblocking.
Write External EEPROM command. Parameters: address to access data, followed by device ID and number of bytes and all data bytes to be written. This command writes the contents of a block of external EEPROM memory. Expect at least 1 and no more than DATA_BUFFER_SIZE-4 data bytes to follow.
Initiate a single A/D conversion. One single A/D conversion is done. Parameters: channel number, Gain (not used). Result: Timer 4 bytes, A/D result 2 bytes.
Return Data Block of Current State.
Parameters: none. Result: Length in bytes of data block A block of internal state variables selected according to application. In this case, four averaged A/D measurements, 2 bytes each, unscaled.
Reset the circular buffer pointers.
This command returns the buffer start and end pointers, then sets the start pointer to the end pointer. This effectively sets the buffer to empty. The calling program is then expected to immediately read in all data between the old start and end pointers to ensure that nothing is overwritten. Parameters: none. Result: none.
Reset the Real Time Clock. No parameters.
Jump to the bootloader. This command causes the program to transfer control to the bootloader. Its purpose is to enable firmware uploads at any time. For the AVR MCU this is done by setting the MCU watchdog timer for the shortest period, and continuing its business. A watchdog timer reset will occur pushing it into the bootloader where the wdt will be disabled. This is unsatisfactory but necessary as the compiler could not handle a long jump.
Command not recognized. Returns an error code.
If an error occurred, launch the error processing task, else launch the output transmission task. Follow by rescheduling the suspended receive task.
Definition at line 553 of file batterychargermain.c.
References ADC_FAILURE, ADC_ONCE, ADC_SYNTAX, adcChannel, address, BOOT_SYNTAX, BOOTLOADER_JUMP, bufferEndPointer, bufferStartPointer, cbi, channel, channelValue, CLEAR_PORT_BIT, DATA_BUFFER_SIZE, eepromCount, F_CPU, FALSE, high, inb, INF_BLOCK_START, inputBuffer, inputCommand, inputPacketReceiveID, lastError, low, NO_ERROR, NO_PORT, numberInBytes, numberOutBytes, outputBuffer, outputBusy, outputCommand, outputPacketSend(), outputPacketSendID, processError(), READ_EEPROM, READ_EEPROM_FAIL, READ_EEPROM_SYNTAX, READ_MEMORY, READ_MEMORY_SYNTAX, READ_PORT, READ_PORT_SYNTAX, READ_SRAM, READ_SRAM_SYNTAX, RESET_BUFFER_POINTERS, RESET_BUFFER_POINTERS_SYNTAX, RESET_CLOCK, RESET_CLOCK_SYNTAX, rtcScale, sbi, SET_PORT_BIT, STATE_VARIABLE_SYNTAX, STATE_VARIABLES, SUCCESS_COMMAND, time, timeUnion::timeByte, timeUnion::timeValue, UNIT_INF_ACCESS, UNIT_INF_ACCESS_SYNTAX, UNKNOWN_COMMAND, WRITE_EEPROM, WRITE_EEPROM_FAIL, WRITE_EEPROM_SYNTAX, WRITE_MEMORY, and WRITE_MEMORY_SYNTAX.
Referenced by inputPacketReceive().
void processError (void)
Error Processing task.
If an error has occurred, reset the input buffer and build an error message to be output. Wait for any output processing to finish. Input processing continues but not packet interpretation.
The program can place any number of explanatory bytes in the output buffer from location 1 onwards, setting numberBytes to the number of additional bytes. This is incremented again to cover the additional error code at location 0.
The task completes processing of the command and exits. It is activated by the input task when a message has been received.
Definition at line 529 of file batterychargermain.c.
References ERROR_COMMAND, FALSE, inputPacketReceiveID, lastError, NO_ERROR, numberOutBytes, outputBuffer, outputBusy, outputCommand, outputPacketSend(), and outputPacketSendID.
Referenced by inputPacketReceive(), and processCommand().