BatteryCharger: Control Tasks
Control Tasks
Functions
void initiateControlTask (void)
Launch the Control task.
void measurementTask (void)
void controlTask (void)
void displayTask (void)
Display task.
Variables
volatile uint16_t channelValue [4]
Measurement task.
volatile uint16_t scaledChannelValue [4]
volatile uint8_t numberChannels
volatile uint8_t channelStart
volatile uint8_t channel
volatile uint8_t channelNumber
volatile uint32_t channelSum
volatile uint16_t adcErrorCount
volatile uint16_t sampleCount
volatile uint16_t testCount
volatile uint16_t runCount
volatile uint8_t storeCount
Control task.
Detailed Description
These functions provide the control and display functionality of the Battery Charger application.
Function Documentation
void controlTask (void)
Start the measurement task and wait until it reschedules us.
Float charging - if the voltage is below the threshold, open the source to charge, otherwise short the panel until the voltage drops.
Store some state variable data in external EEPROM every storeInterval (>0) ticks.
Write the new pointers to their location in EEPROM.
Definition at line 404 of file batterychargermain.c.
References BUFFER_START, bufferEndPointer, bufferStartPointer, controlDelayCounter, controlDisable, DATA_BLOCK_SIZE, eepromEnd, FALSE, floatThreshold, high, localEEPROMDevice, low, measureInterval, measurementTask(), measurementTaskID, newBufferEndPointer, openPanel(), scaledChannelValue, shortPanel(), storeCount, storeInterval, time, and timeUnion::timeByte.
Referenced by initiateControlTask().
void displayTask (void)
Display task.
This task tests for user input via a hardware push button and manages the LCD display of system variables and configuration of certain items.
Definition at line 491 of file batterychargermain.c.
References display(), and scaledChannelValue.
Referenced by initiateControlTask(), and ISR().
void initiateControlTask (void)
Launch the Control task.
This task sets up the main control tasks by initializing the EEPROM storage. When ready it initiates the tasks to run regularly and check the battery voltage. This task then terminates.
Setup the external EEPROM for storing the samples. The first 16 bytes are reserved for general control information which includes the buffer pointers needed to recover data when power fails. These pointers are held in locations 8 to 11.
Start the control task that runs forever in a loop.
Start the display task runs at intervals restarted by the timer ISR. Set the timer going once per second
Definition at line 248 of file batterychargermain.c.
References adcShift, BUFFER_START, bufferEndPointer, bufferStartPointer, controlDelayCounter, controlDisable, controlTask(), controlTaskID, displayInterval, displayTask(), displayTaskCounter, displayTaskID, FALSE, high, localEEPROMDevice, low, setErrorCode(), storeInterval, TRUE, and WRITE_EEPROM_FAIL.
Referenced by main().
void measurementTask (void)
Check that all analogue channels are defined and get the necessary scale factors. This needs to happen regularly in case the EEPROM data is changed, so we do this every time.
The channel Identifier (second channel IB location) has the channel type in the upper four bits, and the channel number in the lower.
If the channel type is a configure channel, update the configuration variables
Check that the channel type is Simple A/D
Compute the number of averaging iterations. Note that the channel sums are maintained as 32 bit values so we can average quite aggressively (but more averaging takes up more time).
In the event of an error, we do not add in the measured value, but we must be able to account for the missing elements. We do this by keeping a count of errored values, and when we get a good value, fill in the previous missing values with multiple copies of it. A better way would be to use the average value as a substitute, but this complicates the arithmetic significantly. Such errors are never signalled back.
The summed results need to be scaled back to 10 bits to match the A/D precision.
The scaled result according to calibration is also stored for display.
Definition at line 314 of file batterychargermain.c.
References _BV, adcErrorCount, adcShift, channel, channelNumber, channelStart, channelSum, channelValue, controlDisable, controlTaskID, FALSE, floatThreshold, measureInterval, numberChannels, rescale(), sampleCount, scaledChannelValue, and storeInterval.
Referenced by controlTask().
Variable Documentation
volatile uint16_t adcErrorCount
Definition at line 309 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint8_t channel
Definition at line 306 of file batterychargermain.c.
Referenced by measurementTask(), and processCommand().
volatile uint8_t channelNumber
Definition at line 307 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint8_t channelStart
Definition at line 305 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint32_t channelSum
Definition at line 308 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint16_t channelValue[4]
Measurement task.
This task measures the voltages and currents from the A/D converters, and scales them according to the calibrated values in the internal EEPROM block. The results are stored in two global arrays: one for the unscaled and one for the scaled values respectively. The order of entries follows the channel number order which must be set correctly by the configuration program to match the A/D converter input numbers.
Since we are checking the channel blocks for the Simple A/D converter information blocks, we also update any other configuration parameters if we come across a general configuration block. All other information blocks are ignored.
Definition at line 302 of file batterychargermain.c.
Referenced by measurementTask(), and processCommand().
volatile uint8_t numberChannels
Definition at line 304 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint16_t runCount
Definition at line 312 of file batterychargermain.c.
volatile uint16_t sampleCount
Definition at line 310 of file batterychargermain.c.
Referenced by measurementTask().
volatile uint16_t scaledChannelValue[4]
Definition at line 303 of file batterychargermain.c.
Referenced by controlTask(), displayTask(), and measurementTask().
volatile uint8_t storeCount
Control task.
This task runs the main control of the Battery Charger and relinquishes when possible to allow serial input and output to occur. Sample data is stored to EEPROM at intervals. This task has absolute priority.
The task runs forever but at the end of the code it enters a timed wait state to allow other tasks to run, otherwise the serial communications and user interface can be disrupted.
Definition at line 402 of file batterychargermain.c.
Referenced by controlTask().
volatile uint16_t testCount
Definition at line 311 of file batterychargermain.c.