BatteryCharger: Board Specific Hardware Functions
Board Specific Hardware Functions
Functions
void configurePorts (void)
Configure the ports to match hardware.
void openPanel (void)
Port B output 0 when high will open the panel for charging.
void shortPanel (void)
Port B output 0 when low will short the panel.
void connectLoad (void)
Port B output 1 when low will connect the battery to the load.
void isolateLoad (void)
Port B output 1 when high will isolate the load.
void onLED (void)
Port B output 2 when low will turn off a LED.
void offLED (void)
Port B output 2 when high will turn on a LED.
Detailed Description
These functions pull together all code that relates to hardware and port manipulations specific to the particular microntroller board and the specific microcontroller used. These may change if a different board or microcontroller is used.
The board is a custom designed board with external EEPROM storage, UART and a buffer or jumpers to read a 4-bit board ID. The SPI programming port may also be buffered. In this example an ATMega168 is used.
Function Documentation
void configurePorts (void)
Configure the ports to match hardware.
Set PORTD as outputs on bits 2-7 to set the LCD. Note that some outputs on this port overlap with ID read inputs. On a controller board that has no hardware buffer to protect these pins, disconnect any jumpers connected to those pins. Leave the UART lines PD0,PD1 alone.
Also set the Power Control register PRR to turn off timer2, timer1, analogue comparator, SPI and also ADC (which will be re-enabled later).
Definition at line 1368 of file batterychargermain.c.
References inb, outb, and sbi.
Referenced by main().
void connectLoad (void)
Port B output 1 when low will connect the battery to the load.
Definition at line 1399 of file batterychargermain.c.
References cbi.
Referenced by main().
void isolateLoad (void)
Port B output 1 when high will isolate the load.
Definition at line 1407 of file batterychargermain.c.
References sbi.
void offLED (void)
Port B output 2 when high will turn on a LED.
Definition at line 1423 of file batterychargermain.c.
References sbi.
Referenced by setErrorCode().
void onLED (void)
Port B output 2 when low will turn off a LED.
Definition at line 1415 of file batterychargermain.c.
References cbi.
Referenced by setErrorCode().
void openPanel (void)
Port B output 0 when high will open the panel for charging.
Definition at line 1383 of file batterychargermain.c.
References sbi.
Referenced by controlTask(), and main().
void shortPanel (void)
Port B output 0 when low will short the panel.
Definition at line 1391 of file batterychargermain.c.
References cbi.
Referenced by controlTask().